language: erlang
services: [docker]
otp_release:
  - 21.0
env:
  - VERBOSE=1
script:
  - |
    set -exv
    export DOCKER_IMG_PROTOC=znly/protoc:0.3.0
    mkdir /tmp/protobuf
    docker pull "$DOCKER_IMG_PROTOC"
    docker run --rm "$DOCKER_IMG_PROTOC" --version
    .travis/extract-protobuf-from-docker.sh /tmp/protobuf
    export PROTOC=$PWD/.travis/docker-protoc.sh
    export CFLAGS=-I/tmp/protobuf/include
    export LDFLAGS=-L/tmp/protobuf/lib
    export LD_LIBRARY_PATH=/tmp/protobuf/lib:$LD_LIBRARY_PATH
    ldd /tmp/protobuf/lib/libprotobuf.so
    make
    make test
